pattern_cols: 10
pattern_rows: 7
center_distance_mm: 40

# 云台坐标系到 IMU 本体坐标系的变换
gimbal2imubody:
  xyz: [0, 0, 0]                    # m 平移
  rpy: [0, 0, 0]                    # rad [yaw, pitch, roll]

camera_name: "hikrobot"
exposure_ms: 3
gain: 10.0
vid_pid: "2bdf:0001"

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"