pattern_cols: 10
pattern_rows: 7
center_distance_mm: 40

R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1]

camera_name: "hikrobot"
exposure_ms: 3
gain: 10.0
vid_pid: "2bdf:0001"

auto_exposure:
  enable: false
  target_brightness: 25.0
  tolerance: 3.0
  step_gain: 15.0
  decay_step: 1.0
  exposure_min: 200.0
  exposure_max: 3500.0
  control_interval_ms: 300

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"
